bookstore/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('book/add/<int:book_id>/', views.basket_add, name='basket_add'),
    path('book/remove/<int:basket_id>/', views.basket_remove,
         name='basket_remove'),
    path('book/<int:pk>/', views.book, name='book'),
    path('genre/<int:pk>/', views.genre, name='genre'),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('books.urls', namespace='books')),
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookstore/users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(next_page='books:index'),
         name='logout')
]

bookstore/books/models.py
from django.db import models

from users.models import CustomUser


class BookGenre(models.Model):
    name = models.CharField(max_length=25, verbose_name='Название жанра')
    description = models.TextField(null=True, blank=True,
                                   verbose_name='Описание')

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название книги')
    description = models.TextField(null=True, blank=True,
                                   verbose_name='Описание')
    price = models.DecimalField(max_digits=6, decimal_places=2,
                                verbose_name='Цена')
    author = models.CharField(max_length=50, verbose_name='Автор')
    image = models.ImageField(upload_to='book.images', null=True,
                              blank=True, verbose_name='Изображение')
    genre = models.ForeignKey(to=BookGenre, on_delete=models.CASCADE,
                              verbose_name='Жанр')

    class Meta:
        ordering = ['name']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return f'Книга: {self.name}, категория: {self.genre}'


class Basket(models.Model):
    quantity = models.SmallIntegerField(default=0,
                                        verbose_name='Количество товара')
    generated_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Когда товар был добавлен в корзину'
    )
    user = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE,
                             verbose_name='Книга')

    class Meta:
        ordering = ['-generated_timestamp']
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return f'Корзина с {self.book} для {self.user}'

    def sum(self):
        return self.book.price * self.quantity

bookstore/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users.images', null=True,
                              blank=True, verbose_name='Изображение')

bookstore/users/forms.py
from django.contrib.auth.forms import (AuthenticationForm,
                                       UserCreationForm,
                                       UserChangeForm)

from .models import CustomUser


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'email',
                  'password1', 'password2']


class UserProfileForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

bookstore/books/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from .models import *

from django.core.paginator import Paginator


def index(request):
    books = Book.objects.all()
    genres = BookGenre.objects.all()
    books_per_page = 6
    paginator = Paginator(books, books_per_page)
    page_number = request.GET.get('page')
    page_books = paginator.get_page(page_number)
    context = {'title': 'Bookstore', 'books': page_books, 'genres': genres}
    return render(request, 'books/index.html', context)


def book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    context = {'book': book}
    return render(request, 'books/book.html', context)


def genre(request, pk):
    book_list = Book.objects.filter(genre=pk)
    book_genre = BookGenre.objects.filter(pk=pk)
    context = {'book_list': book_list, 'book_genre': book_genre}
    return render(request, 'books/genre.html', context)


def basket_add(request, book_id):
    book = Book.objects.get(id=book_id)
    basket = Basket.objects.filter(user=request.user, book=book)
    if not basket.exists():
        Basket.objects.create(user=request.user, book=book, quantity=1)
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

bookstore/users/views.py
from django.shortcuts import render, HttpResponseRedirect

from django.urls import reverse

from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm

from django.contrib import auth

from django.contrib.auth.decorators import login_required

from books.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('books:index'))
    else:
        form = UserLoginForm()
    context = {'form': form, 'title': 'Авторизация'}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form, 'title': 'Регистрация'}
    return render(request, 'users/registration.html', context)


@login_required(login_url='users:login')
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user,
                               files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    basket = Basket.objects.filter(user=request.user)
    total_sum = sum(basket.sum() for basket in basket)
    total_quantity = sum(basket.quantity for basket in basket)
    context = {'title': 'Личный кабинет', 'form': form, 'basket': basket,
               'total_sum': total_sum, 'total_quantity': total_quantity}
    return render(request, 'users/profile.html', context)

bookstore/books/templates/books/book.html
{% load static %}
<html>
<head>
    <title>{{ book.name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
            <li><a href="{% url 'users:login' %}">Войти</a></li>
            <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
            <li><a href="{% url 'users:profile' %}">Личный кабинет</a></li>
            <li><a href="{% url 'admin:index' %}">Админ-панель</a></li>
        </ul>
    </nav>
</header>
<div class="book-info">
    <h1>{{ book.name }}</h1>
    <p>{{ book.description }}</p>
    <p>Цена: {{ book.price }}</p>
    <p>Автор: {{ book.author }}</p>
    <img src="{{ media }}{{ book.image.url }}">
    <p>Жанр: {{ book.genre }}</p>
    <p><a href="{% url 'books:basket_add' book.id %}"><button>Добавить в корзину</button></a></p>
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>

bookstore/books/templates/books/genre.html
{% load static %}
<html>
<head>
    <title>
        {% for genre in book_genre %}
            {{ genre.name }}
        {% endfor %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
            <li><a href="{% url 'users:login' %}">Войти</a></li>
            <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
            <li><a href="{% url 'users:profile' %}">Личный кабинет</a></li>
            <li><a href="{% url 'admin:index' %}">Админ-панель</a></li>
        </ul>
    </nav>
</header>
<div class="book-list">
    {% for book in book_list %}
        <div class="book-item">
            <p><img src="{{ media }}{{ book.image.url }}"></p>
            <p><h3>{{ book.name }}</h3></p>
            <p>Цена: {{ book.price }} руб.</p>
            <p><a href="{% url 'books:book' book.id %}">Информация о книге</a></p>
            <p><a href="{% url 'books:basket_add' book.id %}"><button>Добавить в корзину</button></a></p>
        </div>
    {% endfor %}
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>

bookstore/books/templates/books/index.html
{% load static %}
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
            <li><a href="{% url 'users:login' %}">Войти</a></li>
            <li><a href="{% url 'users:registration' %}">Регистрация</a></li>
            <li><a href="{% url 'users:profile' %}">Личный кабинет</a></li>
            <li><a href="{% url 'admin:index' %}">Админ-панель</a></li>
        </ul>
    </nav>
</header>
<div class="content">
    <aside class="sidebar">
        <ul>
            {% for genre in genres %}
                <li><a href="{% url 'books:genre' genre.id %}">{{ genre.name }}</a></li>
            {% endfor %}
        </ul>
    </aside>
    <section class="main-section">
        <div class="book-list">
            {% for book in books %}
                <div class="book-item">
                    <img src="{{ book.image.url }}" alt="{{ book.name }}">
                    <h3>{{ book.name }}</h3>
                    <p>Цена: {{ book.price }} руб.</p>
                    <p><a href="{% url 'books:book' book.id %}">Информация о книге</a></p>
                    <p><a href="{% url 'books:basket_add' book.id %}"><button>Добавить в корзину</button></a></p>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if books.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ books.previous_page_number }}">предыдущая</a>
                {% endif %}

                <span class="current-page">
                    Страница {{ books.number }} из {{ books.paginator.num_pages }}.
                </span>

                {% if books.has_next %}
                    <a href="?page={{ books.next_page_number }}">следующая</a>
                    <a href="?page={{ books.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>

bookstore/users/templates/users/login.html
{% load static %}
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
        </ul>
    </nav>
</header>
<div class="login-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Авторизоваться">
    </form>
    <div>
        <ul>
            <li>
                <a href="{% url 'users:registration' %}">
                    Ещё не зарегистрировались?</a>
            </li>
        </ul>
    </div>
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>

bookstore/users/templates/users/profile.html
{% load static %}
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
            <li><a href="{% url 'users:logout' %}">Выйти</a></li>
        </ul>
    </nav>
</header>
<div class="profile">
    <h3>Ваш профиль</h3>
    <section>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <img src="{{ form.instance.image.url }}">
            {{ form.as_p }}
            <input type="submit" value="Сохранить">
        </form>
    </section>
    <section>
        <h3>Корзина товаров</h3>
        {% if basket %}
            <ul>
                {% for basket_item in basket %}
                    <li>{{ basket_item.book.name }}</li>
                    <li>{{ basket_item.quantity }}</li>
                    <li>{{ basket_item.sum }}</li>
                    <li><a href="{% url 'books:basket_remove' basket_item.id %}">Удалить товар из корзины</a></li>
                {% endfor %}
                <li>Итоговая сумма: {{ total_sum }}</li>
                <li>Количество добавленных товаров: {{ total_quantity }}</li>
                <li><button>Оформить заказ</button></li>
            </ul>
        {% else %}
            Корзина пуста
        {% endif %}
    </section>
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>

bookstore/users/templates/users/registration.html
{% load static %}
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'books:index' %}">Главная</a></li>
        </ul>
    </nav>
</header>
<div class="registration-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Зарегистрироваться">
    </form>
</div>
<footer>
    <p>&copy; Bookstore 2023</p>
</footer>
</body>
</html>